version: '3.3'

services:

#
# Extra docker ldap stuffs
#

    ldap:
        image: osixia/openldap:1.1.8
        container_name: test-ldap
        # hostname : ldap.example.org
        # network: host
        hostname: ldap
        ports:
          - 389:389
          - 636:636
        volumes:
            - ./ldap_entries:/ldap_entries/
            # :/var/lib/ldap
            # /etc/ldap/sladp.d
    ldapadmin:
        image: osixia/phpldapadmin:0.7.1
        container_name: test-ldapadmin
        hostname: ldapadmin
        # hostname: ldapadmin.example.org
        links:
            - ldap:ldapadmin
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: "ldapadmin"
            PHPLDAPADMIN_HTTPS=false:


volumes:
    sbc_data:
    cc_data:
